config/routes.rb
Rails.application.routes.draw do

root 'pages#index'
  get 'pages/finished'
  get 'pages/help'

  # 以下がどういった経緯だったか
  # rails g controller Sessions new でできたものだろう
  # get 'sessions/new'

  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources 'users'
  # usersというパスで、慣習により、indexにとぶ
  resources 'topics'

  # rails g controller favorites indexで作成された
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  get '/favorites', to: 'favorites#index'

  get '/comments', to: 'comments#new'
  post '/comments', to: 'comments#create'
  # get '/topics', to: 'comments#index'

end

# rails(rake) routes でチェックする
# 上記のようなルーティングをした後に、対応するコントローラのアクションを定義する

# GETは取得（こちらは表示）、POSTは作成、PATCHは更新

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true

  belongs_to :user
  belongs_to :topic

  has_many :favorites
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  belongs_to :comment
end

app/models/topic.rb
# 画像をアップロードするモデル。

class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments
  has_many :comment_users, through: :comments, source: 'user'

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  # userもtopicも↑
  has_many :comments
  has_many :comments_topics, through: :comments, source: 'topic'

  has_secure_password
end

# has_secure_password を使うことで、
 # 暗号化されたパスワードを、DB内の password_digest というカラムに保存できるようになる。
 # password と password_confirmationが使えるようになる。
 # 存在性と値が一致するかどうかのバリデーションも追加される。
 # 引数の文字列がパスワードと一致するとUserオブジェクトを、間違っているとfalseを返すメソッド、authenticateメソッドが使えるようになる。
# 内部で暗号化を行う際に、bcyptというgemを使用するためインストールの必要あり。

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

# controllerで共通で使用するコード

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all.includes(:favorite_users)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(params[:description])
    if @comment.save
      redirect_to topics_path, notice: 'コメントしました'
    else
      flash.now[:alert] = "コメントに失敗しました"
      render :new
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    # @がついていないから、これはインスタンス変数ではないのか
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    if favorite.save
      redirect_to topics_path, notice: 'お気に入りに登録しました'
    else
      redirect_to topics_path, notice: 'お気に入り登録に失敗しました'
    end
  end
end

# Favoriteクラスのインスタンス、favoriteを生成する
# favorite.user_idに現在ログインしているuser(current_user)のidを代入する
# favorite.topic_idにparams[:topic_id]（後述）を代入する
# favoriteをsaveし、その成否によって、条件分岐を行う

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end

  def finished
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    # emailの情報を取得し、一致するユーザーがいるか検索する。
    # いて、passwordが正しければ、
    if user && user.authenticate(params[:session][:password])
      log_in user
      # ここでsession[:user_id]でログイン情報を保存している。
      redirect_to pages_finished_path, alert: 'ログインに成功しました'
    else
      # ログインに失敗されたことが反映されない。なぜ？
      flash.now[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users)
    # N+1問題への対処として、includesメソッドを使う
    @comments = Comment.all.includes(:favorite_users)
  end

  def new
    @topic = Topic.new
    @comment = Comment.new
  end

  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, notice: '投稿に成功しました'
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

private
def topic_params
  params.require(:topic).permit(:image, :description)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # debugger
    # binding.pry の代わり
    if @user.save
      redirect_to(root_path, notice: '登録が完了しました')
      # noticeを変えれば表示画面を変えることができる
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
      # renderは呼び出すViewを指定するためのメソッド
      # この場合は、saveが失敗すると、newアクションが読み込まれる。
    end
  end

private
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

# paramsはViewでフォームに入力された情報が入っている変数のこと。
# text_fieldに入力されたデータは、submitボタンを押すと、
# paramsにそれぞれのシンボルで格納される。

# privateを使ったメソッドは、classの外部からは呼び出せなくなる。

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

# これがよくわからない。
  def logged_in?
    !current_user.nil?
  end
end

# helperはビューで使用する共通のコード

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">

        <h1 class="text-center">Add Comment</h1>

        <%= form_for @comment do |f| %>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description %>
          </div>
        <%= f.submit "投稿", class: 'btn btn-black btn-block' %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>

            <p class="topic-text">
              <%= topic.description %>
            </p>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
        <div class="container">
          <%= link_to root_path do %>
            <span><%= image_tag 'icons/logo.png', class: 'navbar-brand' %></span>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li>
                <%= link_to favorites_index_path do %>
                  <%= image_tag 'icons/heart.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to new_topic_path do %>
                  <%= image_tag 'icons/camera.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to logout_path, method: :delete do %>
                  <%= image_tag 'icons/logout.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_path do %>
                  <%= image_tag 'icons/register.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to login_path do %>
                  <%= image_tag 'icons/login.png' %>
                <% end %>
              </li>
            <% end %>
          </ul>

        </div>
      </nav>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/finished.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Welcome to Pictgram</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
  </div>
</div>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign in', '#', class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', '#', class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3 ">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <!--以下のコードは何を意味しているのか-->
            <%= image_tag topic.image.url %>

            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
              <!--pathの引数にシンボルを与えることで、link_toにパラメーターを渡すことができる-->
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <% end %>
            <% end %>
            <!--こちらにはelse設定しない、trueの反対のfalseで表示されなくなるから-->
            <%= link_to comments_path(topic_id: topic.id), method: :post do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>

            <p class="topic-text">
              <%= topic.description %>
            </p>

            <% @comments.each do |comment| %>
            <p class="comment-text">
              <%= comment.description %>
            </p>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!--favorite.controllerの params[:topic_id] に topic.id がはいる-->

<!--N+1問題（ループごとにtopicをお気に入りしているユーザーを取得するSQLが走り、データベースへの処理が入ることで、処理が重くなってしまうこと）を防ぐためには、includesメソッドを使用する-->

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">

        <h1 class="text-center">Add Picture</h1>

        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :imgage %>
            <%= f.file_field :image %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
        <%= f.submit "投稿", class: 'btn btn-black btn-block' %>
        <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <!--なぜ new_user_path なのか、createかと思った-->
        <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">

        <h1 class="text-center text-white">Sign in</h1>
        <!--↑の””：これって果たして効いてるの？どこかで定義したっけ-->

        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        <%= f.submit "登録", class: 'btn-block btn-white' %>
      <% end %>

      <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>